#!/bin/sh

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##############################################################################

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS="-Xmx64m -Xms64m"

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn () {
    echo "$*"
}

die () {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support.
case "`uname`" in
  CYGWIN*|MINGW*|MSYS*)
    unix_path() {
      echo "$1" | sed 's/\\\\/\//g'
    }
    ;;
  *)
    unix_path() {
      echo "$1"
    }
    ;;
esac

# Attempt to set APP_HOME
PRG="$0"
# Need this for relative symlinks.
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done
SAVED="`pwd`"
cd `dirname "$PRG"` >/dev/null
APP_HOME="`pwd -P`"
cd "$SAVED" >/dev/null

WRAPPER_JAR="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$WRAPPER_JAR" ]; then
    if command -v gradle >/dev/null 2>&1; then
        exec gradle "$@"
    fi
    die "Gradle wrapper JAR not found at $WRAPPER_JAR and no system Gradle installation detected."
fi

CLASSPATH="$WRAPPER_JAR"

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD="java"
fi

if [ ! -x "$JAVACMD" ] ; then
    die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
fi

# Increase the maximum file descriptors if we can.
if [ "$MAX_FD" != "maximum" ] ; then
    ulimit -n $MAX_FD >/dev/null 2>&1 || warn "Could not set maximum file descriptor limit: $MAX_FD"
else
    MAX_FD=`ulimit -H -n`
    if [ $? -eq 0 ]; then
        ulimit -n $MAX_FD >/dev/null 2>&1 || warn "Could not set maximum file descriptor limit: $MAX_FD"
    fi
fi

# For Cygwin or MSYS, convert paths to Windows format before running java
case "`uname`" in
  CYGWIN*|MINGW*|MSYS*)
    APP_HOME=`unix_path "$APP_HOME"`
    CLASSPATH=`unix_path "$CLASSPATH"`
    JAVACMD=`unix_path "$JAVACMD"`
    ;;
esac

exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
  -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
